### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lolbuilderman**
I am testing a simple commit edit from within the github website service Feel free to discuss this change with me
//lolbuilderman

### CODE REVIEW

**Comment by lolbuilderman** [comment]
This seems like a  reasonable change in the program

**Comment by villywebb** [comment]
wow this looks great !!!// villywebb

**Comment by lolbuilderman** [comment]
So is it in the master code now?

**Comment by villywebb** [comment]
im mergin rn !

**Comment by villywebb** [comment]
did not know you were attending the world scout jamboree

**Comment by lolbuilderman** [comment]
No but i believe I don't need any practise since I was the third fastest in my high school! 😅

**Pull request merged**
